site_name: Documentation FreshRSS
theme: readthedocs
site_url: http://doc.freshrss.org
repo_url: https://github.com/FreshRSS/FreshRSS
docs_dir: .

pages:
- Accueil: index.md
- Contribuer à FreshRSS: 03_Contribuer_à_FreshRSS.md
